<script src="{{asset('/assets/front/js/jquery-1.9.1.min.js')}}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{{asset('/assets/front/js/gomap.js')}}"></script>
<script src="{{asset('/assets/front/js/scripts.js')}}"></script>
<script src="{{asset('/assets/front/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery-ui.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery.tweet.js')}}"></script>
<script src="{{asset('/assets/front/js/jflickrfeed.min.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery.matchHeight-min.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery.ba-outside-events.min.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery.themepunch.revolution.min.js')}}"></script>
<script src="{{asset('/assets/front/js/jquery.themepunch.tools.min.js')}}"></script>
<script src="{{asset('/assets/front/js/gmap3.min.js')}}"></script>